server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lidonghui-github/aispringcloud.git
          search-paths: config
          username: lidonghui-github
          password: ab2010678720
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/